### ISSUE TITLE
Build failure QJsonValue::QJsonValue(const *) is private

### ISSUE THREAD

**Issue by williamkibira** [HamedMasafi/Nut#1]
Hello 
On trying to build both the tests , basic example and attempting to use it in my example , i get this error ,

/usr/include/qt5/QtCore/qjsonvalue.h: In member function ‘QJsonObject TableModel::toJson() const’:
/usr/include/qt5/QtCore/qjsonvalue.h:119:12: error: ‘QJsonValue::QJsonValue(const void*)’ is private
     inline QJsonValue(const void *) {}
            ^
../../src/tablemodel.cpp:282:62: error: within this context
         fieldObj.insert(__TYPE, QVariant::typeToName(f->type));
                                                              ^
make: *** [tablemodel.o] Error 1

Any idea you could give me to get this ORM to build ?

**Comment by HamedMasafi** [comment]
Hi, Thanks for reporting. 
Please let me know which version of Qt you're using.

And please make a test:
In file tablemodel.cpp line 292 change the whole line from
` fieldObj.insert(__TYPE, QVariant::typeToName(f->type));`
to
` fieldObj.insert(__TYPE, QJsonValue(QVariant::typeToName(f->type)));

And qmake & clean

Thanks

**Comment by williamkibira** [comment]
on calling qmake -v , the out put i get is

QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu

The error persists with the following output in the terminal

/usr/include/qt5/QtCore/qjsonvalue.h:119:12: error:
‘QJsonValue::QJsonValue(const void*)’ is private

     inline QJsonValue(const void *) {}
            ^
../../src/tablemodel.cpp:282:73: error: within this context
         fieldObj.insert(__TYPE, QJsonValue(QVariant::typeToName(f->type)));
                                                                         ^
make: *** [tablemodel.o] Error 1

I am trying to compile the example inside Nut-master/test/basic/

**Comment by HamedMasafi** [comment]
I'm installed version 5.2.1 on my linux and tested. There are no such error. Can you please take another test:
Change these line to:
`        fieldObj.insert(__TYPE, QString(QVariant::typeToName(f->type)));`

**Comment by williamkibira** [comment]
On changing to QString , it does compile.

-----Original Message-----

**Comment by HamedMasafi** [comment]
Good news. I will apply in next commit.

**Comment by williamkibira** [comment]
I am going to test it out with QSQLITE driver , thank you for your help

-----Original Message-----
