### ISSUE TITLE
Q_OUTOFLINE_TEMPLATE Row<T> Query<T>::first() return nullptr error

### ISSUE THREAD

**Issue by allowwind** [HamedMasafi/Nut#119]
Q_OUTOFLINE_TEMPLATE Row<T> Query<T>::first()
{
    skip(0);
    RowList<T> list = toList(1);

    if (list.count())
        return list.first();
    else
        return nullptr;
}

In file included from ../../Nut/src/database.cpp:42:0:
../../Nut/src/query.h: In instantiation of ‘Nut::Row<T> Nut::Query<T>::first() [with T = Nut::ChangeLogTable; Nut::Row<T> = QSharedPointer<Nut::ChangeLogTable>]’:
../../Nut/src/database.cpp:283:21:   required from here
../../Nut/src/query.h:380:16: error: could not convert ‘nullptr’ from ‘std::nullptr_t’ to ‘Nut::Row<Nut::ChangeLogTable> {aka QSharedPointer<Nut::ChangeLogTable>}’
         return nullptr;
                ^

**Comment by allowwind** [comment]
qt 5.6.1 linux

**Comment by HamedMasafi** [comment]
Hi
Did you tried using c++11 ?
