### ISSUE TITLE
tst_basic sample Nothing created,just __change_logs table created

### ISSUE THREAD

**Issue by Wangpeiyu** [HamedMasafi/Nut#122]
**Describe the bug**
I have tested tst_basic sample with Qt console application in vs2019, but nothing create in database just __change_logs table created.
the output in console window:
![image](https://user-images.githubusercontent.com/7277811/153528596-c9ff90a2-7f25-4362-a9c5-0fd0ad66768c.png)
the result in Mysql WorkBench:
![image](https://user-images.githubusercontent.com/7277811/153528689-304a70ba-cd0d-4196-9d71-42226b137dd3.png)

My code structure:
![image](https://user-images.githubusercontent.com/7277811/153528751-e06c04e7-5ca8-4851-a789-3e101f261cf5.png)

Is there something wrong with my code?

**Development platform:**
 - OS: [Win10 x64]
 - Qt version [e.g. 5.14.2]
 - Compiler [e.g. vs2019]
 - Database [MYSQL8.0]

**Comment by HamedMasafi** [comment]
Hi
Thanks for reporting

Can you please test it with qt6 branch?

**Comment by Wangpeiyu** [comment]
OK, I will test with qt6 branch in next day.

**Comment by Wangpeiyu** [comment]
I have tested with Qt6 branch  tst_basic sample with Qt console application in vs2019，but nothing create in database just __change_logs table created too.
I test the default branch "tests.pro project" with Qt Creator ,everything was going well,may be something wrong with compile setting in vs2019.

**Comment by Wangpeiyu** [comment]
I have debuged with Qt5Nut resource code (vs2019),found q->metaObject()->classInfoCount() in database.cpp line 216 return 0 ,this line is use for create table list.
![image](https://user-images.githubusercontent.com/7277811/154008239-a43e991a-79e3-406a-93a6-2e891f2ffaa3.png)
how to fix it?
