### ISSUE TITLE
Use QUuid as Primary key

### ISSUE THREAD

**Issue by majidkamali1370** [HamedMasafi/Nut#2]
Hi.
Can I use QUuid as table primary key?
```c++
NUT_PRIMARY_AUTO_INCREMENT(id)
NUT_DECLARE_FIELD(QUuid, id, id, setId)
```

How about auto generating `QUuid`s ? Is it handled by database? or I should add id manually?

Thanks :-)

**Comment by HamedMasafi** [comment]
Hi majid
For now QUuid is not supported in _Nut_ but if you like to have it, I can write some codes.

**Comment by majidkamali1370** [comment]
It would be good to have QUuid supported :-)
Does _Nut_ assumes that id column of database is always Int?

Thanks :-)

**Comment by HamedMasafi** [comment]
It will be implemented as soon as possible.

No _Nut_ supports wide range of data types for example for mysql database it support this types:

- bool => boolean
- QByteArray => blob
- QDateTime => datetime
- QDate => date
- QTime => time
- double, qreal => real
- int, qintx => int
- QString => varchar (or text)

For other databases (includes Sql Server, Postgresql, sqlite) _Nut_ supports this types too.
