### ISSUE TITLE
PostgreSQL does not support brackets in alias name

### ISSUE THREAD

**Issue by omarpta** [HamedMasafi/Nut#22]
field AS [table.field] is not support by PostgreSQL and some others databases. 
Please change it so a ANSI version with double quotes.
field AS "table.field"

thks

**Comment by omarpta** [comment]
please avoid `table` too... please, change to "table"

**Comment by HamedMasafi** [comment]
Hi @omarpta 
Want to make a pull request?

**Comment by omarpta** [comment]
Hi @HamedMasafi , 
Done.
