### ISSUE TITLE
Can I use direct objects without having to customize the Database class?

### ISSUE THREAD

**Issue by xdien** [HamedMasafi/Nut#3]
I see in the test library, all objects must be saved through a custom and pre-registered database class. Is there any way to use that without passing the Database class? thank you very much

**Comment by HamedMasafi** [comment]
Greeting.
No, that's impossible in _Nut_. Database class determine related database name, table name, mapped fields and connection info, so it's not possible to store data in database without it.
If mean is different than this, please make it clear.

**Comment by xdien** [comment]
Thank you, you have made a great library.
