### ISSUE TITLE
Cannot remove from database

### ISSUE THREAD

**Issue by LinArcX** [HamedMasafi/Nut#31]
Hi. i have a favorites table(for a music app) and i want to remove some items from it. i wrote this method:
```
virtual void removeFromFavorites(QString title, QString path) override
    {
        Query<Favorites>* q = db.favorites()->query()->setWhere(Favorites::titleField() == title && Favorites::pathField() == path);

        q->toList();

        Favorites* fav = q->first();
        db.favorites()->remove(fav);
        db.saveChanges();
    }
```
but __q__ is null. and subsequently the application crashes. although in db, i have a record like this:
`Marshall-Bruce Mathers. III  |   /home/linarcx/Music/06.justlikeit.mp3`
why?

**Comment by HamedMasafi** [comment]
The _q_ should not be null. Query<T>::setWhere returns this so q will be query itself.
https://github.com/HamedMasafi/Nut/blob/master/src/query.h#L452

Can you please send database and table class for testing?

**Comment by LinArcX** [comment]
Oh, __q__ is filling:)
I remove first condition and everything work!
Is there any restrictions to pass 2 Qstrings in  __where__ clause?

**Comment by HamedMasafi** [comment]
No. there is not any restrictions. But your terms may not return a result. Check your data if there is a record with the given terms.
