### ISSUE TITLE
Support for an additional build system generator

### ISSUE THREAD

**Issue by elfring** [HamedMasafi/Nut#32]
I suggest to reuse a higher level build system additional to [your current build script](https://github.com/HamedMasafi/Nut/blob/7f5e967f57e48b8bfa8bb73bd36f5a462769d4b7/nut.pro#L1 "Qt build approach") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by HamedMasafi** [comment]
Any pull requests are welcome
