### ISSUE TITLE
qstrings can cause sql errors depending on contents

### ISSUE THREAD

**Issue by eyecreate** [HamedMasafi/Nut#37]
When a QString has a single quote in it, it breaks the sql statements because the raw commands use single quotes to contain content. There should be something handling this case, like escaping them.

ex:
```
Error executing sql command: near "s": syntax error Unable to execute statement; Command=UPDATE purchases SET humanname='Sid Meier's Civilization® III: Complete', type='storefront', intname='civilization3_complete_storefront', humbleid='' WHERE id=1
```

**Comment by HamedMasafi** [comment]
Thanks for bug report. I've written a library for this issue 
https://github.com/HamedMasafi/Serializer

I'm going to integrate it with _Nut_ then nut can store any data type that supports by QMetaType including QPoint(F), QRect(F), QJsonDocument, QRegion and etc

**Comment by HamedMasafi** [comment]
This is fixed in _dev_ branch. and will be merged with _master_ branch ASAP
