### ISSUE TITLE
What requirement is nut?

### ISSUE THREAD

**Issue by liufeijin** [HamedMasafi/Nut#38]
Could you make a list of requirement for using nut?  
I knew  1 requirement is  "mysql connector c " source code. 

I use qt5.12 on windows10.
Many thanks!
jeff

**Comment by HamedMasafi** [comment]
The _Nut_'s dependency is Qt itself. If your Qt can connect to a database then _Nut_ can too. In other words _Nut_ use QSqlDatabase, so there is no other requirement, just make sure your sql driver works fine in your os environment. In your case you should provide mysql c connector and it should be enough.

**Comment by liufeijin** [comment]
Hi HamedMasafi
I use your dev branch build success. 
But got the error "The class Post is not registered with qt meta object' then app crashed.
I will test the master branch soon.
BTW, the package of nut-dev is not include serializer/src. It is empty under the folder of serializer.
Best regards,
jeff

**Comment by liufeijin** [comment]
Hi HamedMasfi
I switched to master branch. when i build it got error as below:
![1](https://user-images.githubusercontent.com/19425403/52633330-f47e4e80-2efe-11e9-9cc6-fe2650144766.png)

**Comment by liufeijin** [comment]
I changed to amreisa's master branch , build success. When run it ,seems can connect to mysql database.
PICs for your reference.
![2](https://user-images.githubusercontent.com/19425403/52633789-6e630780-2f00-11e9-8f98-f8ecae6aa57c.png)

![3](https://user-images.githubusercontent.com/19425403/52633815-7e7ae700-2f00-11e9-970d-6164bee650d2.png)
![4](https://user-images.githubusercontent.com/19425403/52633821-82a70480-2f00-11e9-9246-86e4639d364b.png)

**Comment by HamedMasafi** [comment]
Hi @liufeijin 
The _dev_branch is under development. I'm working on new features. Some unsuitability my occurs. If you want to use new features hold few days the new version is coming. Else switch to master branch (that is old without new features)
