### ISSUE TITLE
maintest.cpp:102: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’   

### ISSUE THREAD

**Issue by xdien** [HamedMasafi/Nut#4]
I tried running the program but could not build.
`auto q = db.posts()->createQuery();
    q->join(Post::commentsTable());
    q->orderBy(!Post::saveDateField() & Post::bodyField());
    q->setWhere(Post::idField() == postId);
`
How can fix it?
Thanks you

**Comment by HamedMasafi** [comment]
Can you please put full output?

**Comment by xdien** [comment]
Sorry for the late.
All output here when I run tst_basic.pro
`/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp: In member function ‘void MainTest::selectPosts()’:
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:102:26: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’
     auto q = db.posts()->createQuery();
                          ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:104:39: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
     q->orderBy(!Post::saveDateField() & Post::bodyField());
                                       ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp: In member function ‘void MainTest::selectPostsWithoutTitle()’:
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:124:26: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’
     auto q = db.posts()->createQuery();
                          ^
In file included from /home/xdien/workspace/nhansu/Nut/src/database.h:28:0,
                 from /home/xdien/workspace/nhansu/Nut/test/common/weblogdatabase.h:4,
                 from /home/xdien/workspace/nhansu/Nut/test/basic/maintest.h:7,
                 from /home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:7:
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp: In member function ‘void MainTest::selectComments()’:
/home/xdien/workspace/nhansu/Nut/src/defines.h:112:63: error: ‘class Nut::TableSet<Comment>’ has no member named ‘createQuery’
 #   define FROM(x)          /*QScopedPointer<QueryBase*>*/(x->createQuery())
                                                               ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:133:21: note: in expansion of macro ‘FROM’
     auto comments = FROM(post->comments())
                     ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp: In member function ‘void MainTest::testDate()’:
/home/xdien/workspace/nhansu/Nut/src/defines.h:112:63: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’
 #   define FROM(x)          /*QScopedPointer<QueryBase*>*/(x->createQuery())
                                                               ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:154:14: note: in expansion of macro ‘FROM’
     auto q = FROM(db.posts())
              ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp: In member function ‘void MainTest::selectWithInvalidRelation()’:
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:164:26: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’
     auto q = db.posts()->createQuery();
                          ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp: In member function ‘void MainTest::select10NewstPosts()’:
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:171:26: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’
     auto q = db.posts()->createQuery();
                          ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp: In member function ‘void MainTest::modifyPost()’:
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:178:26: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’
     auto q = db.posts()->createQuery();
                          ^
In file included from /home/xdien/workspace/nhansu/Nut/src/database.h:28:0,
                 from /home/xdien/workspace/nhansu/Nut/test/common/weblogdatabase.h:4,
                 from /home/xdien/workspace/nhansu/Nut/test/basic/maintest.h:7,
                 from /home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:7:
/home/xdien/workspace/nhansu/Nut/src/defines.h:112:63: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’
 #   define FROM(x)          /*QScopedPointer<QueryBase*>*/(x->createQuery())
                                                               ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:188:9: note: in expansion of macro ‘FROM’
     q = FROM(db.posts())
         ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp: In member function ‘void MainTest::deletePost()’:
/home/xdien/workspace/nhansu/Nut/src/defines.h:112:63: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’
 #   define FROM(x)          /*QScopedPointer<QueryBase*>*/(x->createQuery())
                                                               ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:197:18: note: in expansion of macro ‘FROM’
     auto count = FROM(db.posts())
                  ^
/home/xdien/workspace/nhansu/Nut/src/defines.h:112:63: error: ‘class Nut::TableSet<Post>’ has no member named ‘createQuery’
 #   define FROM(x)          /*QScopedPointer<QueryBase*>*/(x->createQuery())
                                                               ^
/home/xdien/workspace/nhansu/Nut/test/basic/maintest.cpp:203:13: note: in expansion of macro ‘FROM’
     count = FROM(db.posts())
             ^
make: *** [Makefile:3132: maintest.o] Error 1
07:24:52: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project tst_basic (kit: Desktop Qt 5.8.0 GCC 64bit)`

**Comment by HamedMasafi** [comment]
Sorry that is my mistake, createQuery() renamed to query(). I will push a new commit to correct tests (if you need so) within next 24hrs.
Of course you can do a s/createQuery/query/g

**Comment by xdien** [comment]
I have changed some lines of code, I think it will make this library run more stable. Can you let me contribute it?

**Comment by HamedMasafi** [comment]
In the last commit syntax changes applied to maintest

> I have changed some lines of code, I think it will make this library run more stable. Can you let me contribute it?

Absolutely yes. Make a fork and feel free to pull requests.

**Comment by xdien** [comment]
Thanks you very much!
