### ISSUE TITLE
Can not select data on mysql driver?

### ISSUE THREAD

**Issue by YaoHuan123** [HamedMasafi/Nut#41]
//code
auto q = db.users()->query()
        ->setWhere(User::idField() == "{a5dba5aa-254a-45fc-bee3-a102cfb805f5}");
int num = q->count(); // num is 1;
User* u = q->first(); // u is NULL;

**Comment by YaoHuan123** [comment]
everything is work,but read data is valid,
help!

**Comment by HamedMasafi** [comment]
What is User::id field type and which branch you are using? (master or dev?)

**Comment by YaoHuan123** [comment]
master branch. and app read from mysql server 8.0.

**Comment by YaoHuan123** [comment]
A mysql syntax error on exec
```
template <class T>
Q_OUTOFLINE_TEMPLATE QList<T *> Query<T>::toList(int count){
if (q.lastError().isValid()) {
        qDebug() << q.lastError().text();
        return returnList;
    }
}
```

**Comment by HamedMasafi** [comment]
Please check _dev_ branch

**Comment by HamedMasafi** [comment]
_dev_ merged into _master_ and everything works fine
