### ISSUE TITLE
Add optional parent argument to Query::toModel

### ISSUE THREAD

**Issue by martonmiklos** [HamedMasafi/Nut#62]
Hi @HamedMasafi 

During the usage of the Query::toModel I was wondering if it would be helpful to pass a QObject *parent = nullptr argument to it to make that object to be the parent of the created model here:
https://github.com/HamedMasafi/Nut/blob/master/src/query.h#L592

This would make the created model destruction easily manageable through the QObject destruction process.
What do you think about this idea?
If you like it I can came up with a PR.

**Comment by HamedMasafi** [comment]
Hi @martonmiklos 
ATM I have no idea for toModel part, I have no plan for using QSqlQueryModel or Nut::SqlModel
So I've keep it to later.
I'm busy with new commit of nut that many Table macros will gone. In new model user can create regular qobject based class with Q_PROPERTY. You are free to PR but model scenario may be changed later
