### ISSUE TITLE
Purpose of the NUT_FOREIGN_KEY macro?

### ISSUE THREAD

**Issue by martonmiklos** [HamedMasafi/Nut#69]
Hello @HamedMasafi 

May I ask what was the intention with the NUT_FOREIGN_KEY:
https://github.com/HamedMasafi/Nut/blob/2f439541a4c82345f43b885c9bc8f1fba770edb2/src/defines.h#L85

Is it left in accidentally or it was the start of something? I have not found any reference in the code to it.

I am working on upstreaming my join fix so I will poke around the NUT_FOREIGN_KEY_DECLARE/IMPLEMENT and if I am there it might be useful to remove it to remove confusion.

**Comment by HamedMasafi** [comment]
The NUT_FOREIGN_KEY was first version on master/slave (1:n) join mechanism, but later it spliced into two part of declaration/implementation. I thins it can now be deleted safely.

**Comment by martonmiklos** [comment]
Allright, thanks for the answer, I have removed it in #70
