### ISSUE TITLE
multiple select

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [HamedMasafi/Nut#7]
how can make custom select "SELECT filed1,filed2,filed3 FROM table"

**Comment by HamedMasafi** [comment]
Multiple select is not supported yet. But the _select_ method provide a way for selecting single field.
Some updates is WIP right now:

- Advanced and multilevel joining
- Including and Excluding fields or creating new object based on result (It's cover your question)
- And some cool updates!

I hope new version be ready within few weeks. Watch **master** branch and keep in touch until _dev_ branch merge into _master_.

**Comment by MrAhmedSayedAli** [comment]
i added this code in Database class
`
QList <QVariantMap> Database::sqlToList(QString sql){
    Q_D(Database);
    QList<QVariantMap> allList;
    QStringList fieldNames;
    QSqlQuery q = d->db.exec(sql);
    if (d->db.lastError().type() != QSqlError::NoError){
        qWarning("Error executing sql command: %s; Command=%s",
                 d->db.lastError().text().toLatin1().data(),
                 sql.toUtf8().constData());
    }else{
        while(q.next()) {
            QVariantMap map;
            for(int x=0; x < q.record().count(); x++) {
                map.insert(q.record().fieldName(x), q.value(x));
            }
            allList.append(map);
        }
        q.finish();
    }
    return allList;
}
`
And Test 

`
        auto q = myDb.sqlToList("SELECT TOP 1000 filed1,filed2 FROM Table");
        foreach (QVariantMap c, q) {
            qDebug() << c["filed1"];
            qDebug() << c["filed2"];
        }
`

it work fine But Slow

**Comment by HamedMasafi** [comment]
I aimed to avoid hard-coding. But another solution is in progress.

**Comment by MrAhmedSayedAli** [comment]
@amreisa

**Comment by amreisa** [comment]
Hello @MrAhmedSayedAli @HamedMasafi ...,
I this can done by addFilter() function or use old style printf format string like printf("%s", Filter)
I don't Know What is good for Nut to start work with ?
regrades...,
@amreisa

**Comment by MrAhmedSayedAli** [comment]
@HamedMasafi any update on this

**Comment by HamedMasafi** [comment]
Hi @MrAhmedSayedAli 
This methods avoid non-hardcode rule of an orm, In my view for an orm everything must be in objects and field names should not be written in strings. In other words in this case the compile-time error would not happen while everything is sql command. This type of query can be done without orm. So why we need it?
