### ISSUE TITLE
class not registered with qt meta object

### ISSUE THREAD

**Issue by yangxingpping** [HamedMasafi/Nut#85]
when I cop unittest tst_datetime's db and sampletable class to an simple demo, it cause fatal
for sampletable 
qFatal("The class %s is not registered with qt meta object", qPrintable(name));

code snippet :
    DB db;
    db.setDriver("QSQLITE");
    db.setDatabaseName("hello.db");
    auto bOpen = db.open();

Can  add some additional demos for how to use it?

**Comment by HamedMasafi** [comment]
Hi @yangxingpping 
You need to register the all classes used in _Nut_ (Database and tables) with _qRegisterMetaType_ function. For more information please take a look at tests.

**Comment by yangxingpping** [comment]
Thank you!
