### ISSUE TITLE
add options methods to new version 

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [HamedMasafi/Nut#9]
on DatabasePrivate::open (File : database.cpp)
when called if not find database it direct make `db.exec("CREATE DATABASE " + databaseName);`
but some time we just want to return just error only
so if you can make options methods to that like
`void Database::setCrateDatabase(bool default)`
`void Database::setCrateTables(bool default)`

thanx and sorry for my bad English 😄

**Comment by MrAhmedSayedAli** [comment]
Up

**Comment by MrAhmedSayedAli** [comment]
up

**Comment by HamedMasafi** [comment]
Hi MyAhmet
New version of _Nut_ is much smarter. So it only run database update once. In first instantiate database will be checked and updated to latest version if needed. But in future instantiate _Nut_ doesn't run database update. So, I think the methods you suggest is not necessary. 
In other way _Nut::Database_ has a signature of open method that take a bool:
**Nut::Database::open(bool updateDatabase)**
In this signature of you pass false for _updateDatabase_ the will not be updated.
Please provide  me more information if you need this methods.
BR

**Comment by MrAhmedSayedAli** [comment]
i update to last nut and update my code but i have error on query.h line 110 d->tableName =
(read access violation)

**Comment by MrAhmedSayedAli** [comment]
i have 
qDebug() << "type id:" << qRegisterMetaType<OptionTable*>();
and on tableByClassName function  not return any thing ?!!
