### ISSUE TITLE
It make fail with "sqlserializer.h: No such file or directory"

### ISSUE THREAD

**Issue by s564200489** [HamedMasafi/Nut#93]
1. "qmake nut.pro"
2. "make"

**Output**
`generators\sqlgeneratorbase.cpp:34:27: fatal error: sqlserializer.h: No such file or directory
compilation terminated.
Makefile.Release:818: recipe for target 'release/sqlgeneratorbase.o' failed
make[2]: *** [release/sqlgeneratorbase.o] Error 1
make[2]: Leaving directory 'D:/WorkSpace/Nut-master/src'
Makefile:36: recipe for target 'release' failed
make[1]: *** [release] Error 2
make[1]: Leaving directory 'D:/WorkSpace/Nut-master/src'
Makefile:41: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 2
`

**Development platform:**
 - OS: [e.g. win10 2016 LTSB ]
 - Qt version [e.g. 5.9.9]
 - Compiler [e.g.MingW 5.3.0]

**Comment by HamedMasafi** [comment]
_Nut_ use Serializer lib as a submodule, so please make a *git submodule update*
