### ISSUE TITLE
Linking problem (undefined reference)

### ISSUE THREAD

**Issue by mbnoimi** [HamedMasafi/Nut#97]
Hi,

First of all I'd like to thank you a lot for the great project. Today I tried to create a [tiny example](https://github.com/mbnoimi/ormtest) for testing Nut but I faced a problem with linking Nut in my project so I get many `undefined reference` messages.

May you please guide me how to fix this error?

**OrmTest.pri**
```
win32 {
        CONFIG(debug,debug|release):   LIBDIR = $$absolute_path($$OUT_PWD/../libs/Nut/src/debug)
        CONFIG(release,debug|release): LIBDIR = $$absolute_path($$OUT_PWD/../libs/Nut/src/release)
} else {
        LIBDIR = $$absolute_path($$OUT_PWD/../libs/Nut/src/)
}

LIBS += -L$$LIBDIR -lnut
INCLUDEPATH += $$PWD/../libs/Nut/src/

DEFINES += NUT_SHARED_POINTER
``` 
Project's structure:
```
OrmTest
├── libs
│   └── Nut (submodule)
├── LICENSE
├── OrmTest.pro
└── src
    ├── companyemployees.cpp
    ├── companyemployees.h
    ├── main.cpp
    ├── mainwindow.cpp
    ├── mainwindow.h
    ├── mainwindow.ui
    ├── OrmTest.pri
    ├── OrmTest.pro
    ├── user.cpp
    └── user.h
```

**Comment by HamedMasafi** [comment]
I made some changes to your repo and I sent a pr. Take a look

**Comment by mbnoimi** [comment]
Thanks @HamedMasafi 
Actually I felt so sad because of ignoring my report for 14 days which mean this project not suitable at all for developers.

Any way, I'll take a look into PR to test it.
