### ISSUE TITLE
[1 to many] relations implementation

### ISSUE THREAD

**Issue by JackLilhammers** [HamedMasafi/Nut#98]
I read that [1 to many] relations are implemented with child tables, but I can't see them in the db.
Is it the user's responsibility to explicitly create those tables?
Shouldn't be the ORM the one that creates them?

**Comment by JackLilhammers** [comment]
I realized now that my use case is a [n to m] relation, my bad. I'm closing this issue.
If you're interested I'll reopen it as a feature request.

**Comment by HamedMasafi** [comment]
Hi @JackLilhammers 
Thank you for your interest!
ATM _Nut_ Don't create foreign key on database btw its in my todo plan. 
I will add this feature asap also you can create a feature request.
BR

**Comment by JackLilhammers** [comment]
Thank you for making this project.
I'm an absolute beginner with ORMs, but I'm trying to use it for a project at work, therefore I'll do my best to improve Nut
